name: CI Tests

on:
  push:
    branches: [main, dev, 'fix/**']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver (IMPORTANT)
        run: |
          sudo apt-get install -y chromium-chromedriver
          chromedriver --version

      - run: google-chrome --version

      - run: node tests/form.test.js
        env:
          CI: true